formatter: "markdown table"

sections:
  hide:
    - resources
    - requirements

recursive:
  enabled: true
  path: modules

output:
  file: ./docs/source/TFDOCS.md
  mode: inject

content: |-
  {{ .Header }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}  